spec:
  structures:
    - content_blocks
  label: Steps
  description:
  icon: 'task'
  tags: []

blueprint:
  title: |
    Lorem ipsum <em>dolor sit</em> amet
  steps:
    - title: Lorem ispum
      image: https://dummyimage.com/300x200
      step: '1'
      last_step: false

preview:

_inputs:
  title:
    type: html
