spec:
  structures:
    - content_blocks
  label: Stats
  description:
  icon: 'task'
  tags: []

blueprint:
  stats:
    - title: 'Lorem'
      label: 'Lorem Ipsum'
    - title: 'Lorem'
      label: 'Lorem Ipsum'
    - title: 'Lorem'
      label: 'Lorem Ipsum'
    - title: 'Lorem'
      label: 'Lorem Ipsum'
    - title: 'Lorem'
      label: 'Lorem Ipsum'
    - title: 'Lorem'
      label: 'Lorem Ipsum'

preview:

_inputs:
