spec:
  structures:
    - content_blocks
  label: CTA w/ Plane Bg
  description:
  icon: 'task'
  tags: []

blueprint:
  title: |
    Lorem ipsum <em>dolor sit</em> amet
  description: |
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, <strong>sed do eiusmod tempor incididunt ut</strong> labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
  button:
    label: Button
    url: '#'

preview:

_inputs:
  title:
    type: html
  description:
    type: html
