spec:
  structures:
    - content_blocks
  label: Spacer
  description:
  icon: 'task'
  tags: []

blueprint:
  title: Lorem
  content: |
    lorem ipsum

preview:

_inputs:
  content:
    type: html
