spec:
  structures:
    - content_blocks
  label: Hero Contact
  description:
  icon: 'task'
  tags: []

blueprint:
  title: Lorem ipsum
  subtitle: Lorem ipsum dolor sit amet
  image: /upload/img-hero-contact.svg
  form:
    title: Lorem ipsum
    button: Lorem ipsum

preview:

_inputs:
