spec:
  structures:
    - content_blocks
  label: Title + Multi Side Cols
  description:
  icon: 'task'
  tags: []

blueprint:
  title: |
    Lorem ipsum <em>dolor sit</em> amet
  description: |
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, tortor eget sodales aliquam, nunc nisl ultricies nunc, quis aliquam nisl nisl vitae nunc. Sed euismod, tortor eget sodales aliquam, nunc nisl ultricies nunc, quis aliquam nisl nisl vitae nunc.
  media:
    animation: computer
    image:
  cards:
    - title_card: Lorem ispum
      description_card: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      icon: https://dummyimage.com/50x50

preview:

_inputs:
  title:
    type: html
  description:
    type: html
  animation:
    type: select
    options:
      values:
        - computer
  image:
    comments: If an image is selected, the animation will be hidden
