spec:
  structures:
    - content_blocks
  label: Team
  description:
  icon: 'task'
  tags: []

blueprint:
  team:
    - name: Lorem Ipsum
      position: Lorem ipsum
      bio: |
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p> <p>Duis aute irure dolor in reprehenderit <strong>in voluptate velit esse</strong> cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      image: https://dummyimage.com/400x500
    - name: Lorem Dolor
      position: Lorem ipsum
      bio: |
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p> <p>Duis aute irure dolor in reprehenderit <strong>in voluptate velit esse</strong> cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      image: https://dummyimage.com/400x500

preview:

_inputs:
  bio:
    type: html
