spec:
  structures:
    - content_blocks
  label: International Query
  description:
  icon: 'task'
  tags: []

blueprint:
  title: |
    <em>International</em> Trademark Pricing
  description: Select countries to calculate the final price.
  countries:
    - country_title: Australia
      gov_fee: 100
      service_fee: 100
      icon: https://dummyimage.com/50
      popular: true

preview:

_inputs:
  title:
    type: html
  icon:
    type: image
  country_title:
    type: text
