spec:
  structures:
    - content_blocks
  label: International Query
  description:
  icon: 'task'
  tags: []

blueprint:
  title_section: |
    <em>International</em> Trademark Pricing
  description: |
    Select countries to calculate the final price.

preview:

_inputs:
  title_section:
    type: html
  description:
    type: html
  icon:
    type: image
