spec:
  structures:
    - content_blocks
  label: Testimonials
  description:
  icon: 'task'
  tags: []

blueprint:
  title: |
    Lorem ipsum <em>dolor sit</em> amet
  testimonials:
    - name: Lorem ispum
      position: Lorem ispum
      description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
      icon: https://dummyimage.com/90

preview:

_inputs:
  title:
    type: html
  icon:
    type: image
