spec:
  structures:
    - content_blocks
  label: Search
  description:
  icon: 'task'
  tags: []

blueprint:
  title: |
    Lorem ipsum <em>dolor sit</em> amet

preview:

_inputs:
  title:
    type: html
